#' Dissimilarity Matrix Example
#'
#' A dissimilarity matrix computed with [stats::dist()] on a simulated dataset.
#'
#' @format An object of class [stats::dist()] containing pairwise similarities for (\eqn{n = 20}) objects.
#'
#' @details The object is intended for examples and vignettes.
#'
#' @source Generated by simulating \eqn{n = 20} objects from a two-component mixture distribution and then computing a dissimilarity matrix via [stats::dist()].
#'
#' @usage data(dis_mat_example)
"dis_mat_example"
