#' MCMC Example Output
#'
#' Posterior samples returned by [run_dpcd()] after fitting an Equal Spherical (ES) model to simulated dissimilarities.
#'
#' @format An object of class `mcmc` containing posterior draws for the monitored parameters from the DPCD model fit. It contains 4,000 rows (MCMC iterations) and 110 columns.
#'
#' @details The object is intended for examples and vignettes.
#'
#' @source Generated by fitting an Equal Spherical (ES) DPCD model to the dissimilarities calculated from a small (\eqn{n = 20}) simulated dataset with two mixture components.
#'
#' @usage data(mcmc_example)
"mcmc_example"
