#' MCMC Example Output
#'
#' Posterior samples returned by [run_dpcd()] after fitting an Equal Spherical (ES) model to simulated dissimilarities.
#'
#' @format An object of class `mcmc` containing posterior draws for the monitored parameters from the DPCD model fit. It contains 40,000 rows (MCMC iterations) and 125 columns (model parameters).
#'
#' @details The object is intended for examples and vignettes.
#'
#' @source Generated by fitting an Equal Spherical (ES) DPCD model to the dissimilarities calculated from a simulated dataset (\eqn{n = 50}) with two mixture components.
#'
#' @usage data(mcmc_example)
"mcmc_example"
